### ISSUE TITLE
Errors in "Yarn Install" and "Npm Install" on windows and mac

### ISSUE THREAD

**Issue by Beshoj** [inspireui/mstore#175]
**Hello .. 

I followed this doc: 
https://facebook.github.io/react-native/docs/getting-started.html
And I ran the AwesomeProject  successfully on my device. But when i try to run "yarn install" or "npm install". I got these errors:**

​

**(NPM I) Error:**
```
> react-native-pod@1.10.0 preinstall /Users/basharjarrah/Desktop/Mstore/mstore-pro/node_modules/react-native-pod
> ./bin/preinstall.js

child_process.js:615
    throw err;
    ^

Error: Command failed: which pod
    at checkExecSyncError (child_process.js:575:11)
    at execSync (child_process.js:612:13)
    at Object.<anonymous> (/Users/basharjarrah/Desktop/Mstore/mstore-pro/node_modules/react-native-pod/bin/preinstall.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-pod@1.10.0 preinstall: `./bin/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-pod@1.10.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/basharjarrah/.npm/_logs/2018-04-12T13_14_27_707Z-debug.log

```

"Yarn Install" Error:
```
[4/4] 📃  Building fresh packages...
[1/2] ⢀ fsevents
[2/2] ⢀ react-native-pod
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
error An unexpected error occurred: "/Users/basharjarrah/Desktop/Mstore/mstore-pro/node_modules/react-native-pod: Command failed.
Exit code: 1
Command: sh
Arguments: -c ./bin/preinstall.js
Directory: /Users/basharjarrah/Desktop/Mstore/mstore-pro/node_modules/react-native-pod
Output:
child_process.js:615
    throw err;
    ^

Error: Command failed: which pod
    at checkExecSyncError (child_process.js:575:11)
    at execSync (child_process.js:612:13)
    at Object.<anonymous> (/Users/basharjarrah/Desktop/Mstore/mstore-pro/node_modules/react-native-pod/bin/preinstall.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)".

```

**Please Help!**

**Comment by Beshoj** [comment]
Fixed from the support.. Referring to this link:
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/186#issuecomment-347623033

I only ran these commands:
```
sudo gem install cocoapods
pod repo update
```
